---
driver:
  name: vagrant
  network:
  - ["private_network", {ip: "192.168.33.41"}]

provisioner:
  name: chef_zero

platforms:
  - name: debian-6.0.10
    driver:
      provision: true
      vagrantfiles:
        - vagrant_debian6.rb
  - name: debian-7.8
  - name: debian-8.4

suites:
  - name: agent
    run_list:
      - recipe[t3-zabbix::agent]
    attributes:

  - name: server
    run_list:
      # if we would pin the mysql/database versions here, this would restrict them
      # for all nodes in our infrastructure - to pin them only for the server version,
      # we use this trick for testing.
      # Long story short: server and agent recipes must not go into a single cookbook!
      #   ~ young Steffen
      #
      - recipe[zabbix-server-version-pin]
      - recipe[t3-zabbix::server]
    attributes:

  - name: server-3.0
    run_list:
      - recipe[zabbix-server-version-pin]
      - recipe[t3-zabbix::server]
    attributes:
      zabbix:
        server:
          version: 3.0.4
