---
driver:
  name: vagrant
  network:
  - ["private_network", {ip: "192.168.33.41"}]

provisioner:
  name: chef_zero

platforms:
- name: debian-7.11
  run_list:
    - recipe[apt]
- name: debian-8.6
  run_list:
    - recipe[apt]


suites:
- name: agent
  run_list:
    - recipe[t3-zabbix::agent]
  attributes:

- name: server
  excludes: debian-8.6
  run_list:
    - recipe[t3-zabbix::server]
  attributes:
