---
driver:
  name: vagrant
  network:
  - ["private_network", {ip: "192.168.33.41"}]

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8

suites:
  - name: default
    run_list:
      - recipe[t3-zabbix::default]
    attributes:

  - name: server
    run_list:
      - recipe[t3-zabbix::server]
    attributes:
      zabbix:
        server:
          version: 2.4.5